name: Triggering Code

on:
  repository_dispatch:
    types: [org-workflow-bot]  
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        enforce_admin: true
    - name: Printing variables
      run: |
        echo "commits: ${{ toJson(github.event.client_payload.event.commits[0].modified) }}"
        echo "repository: ${{ github.event.client_payload.repository.full_name }}"
        echo "ref: ${{ github.event.client_payload.sha }}"
        echo "token: ${{ github.event.client_payload.token }}"
        
        commits= ${{ github.event.client_payload.event.commits }}
        
        echo "commits n. ${commits[@]}"
        for i in "${commits[@]}"
        do 
          folder=$(echo $i.modified | awk -F'/' '{print $1}' | tr -d '"' | tr -d '[' | tr -d ']')
          if [[ "$folder" == "googleVisionAI" ]]
          then
            img_list="$img_list google-vision"
          elif [[ "$folder" == "yarpOpenPose" || "$folder" == "faceLandmarks" ]]
          then
            img_list="$img_list human-sensing"
          fi
        done
    
        
        
        
