name: Triggering Code

on:
  repository_dispatch:
    types: [org-workflow-bot]  
   
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        enforce_admin: true
    #- name: Checkout
    #  uses: trilom/file-changes-action@v1.2.3
    #  id: 
    #  with:
    #    repository: ${{ github.event.client_payload.repository.full_name }}
    #    ref: ${{ github.event.client_payload.sha }}
    #    token: ${{ github.event.client_payload.token }}
    - name: Printing variables
      run: |
        echo "repository: ${{ github.event.client_payload.repository.full_name }}"
        echo "ref: ${{ github.event.client_payload.sha }}"
        echo "token: ${{ github.event.client_payload.token }}"
